spec_version: 1.2
package: landex

database:
  kind: sqlite
  path: landex.sqlite3

# Contracts on mainnet
contracts:
  tezlandItems:
    address: KT1TKFWDiMk35c5n94TMmLaYksdXkHuaL112
    typename: tezlandItems

  tezlandPlaces:
    address: KT1G6bH9NVDp8tSSz7FzDUnCgbJwQikxtUog
    typename: tezlandPlaces

  tezlandDAO:
    address: KT1Xag669km4EXaQPi3GH9fcofjvPnJneuaL
    typename: tezlandDAO

  tezlandWorld:
    address: KT1EuSjJgQRGXM18TEu1WaMRyshPSkSCg11n
    typename: tezlandWorld

  tezlandMinter:
    address: KT1GmLfej8mFrfB3bRSoc1fTuCa9eQHJw8Qi
    typename: tezlandMinter

  tezlandDutchAuctions:
    address: KT1WmMn55RjXwk5Xb4YE6asjy5BvMiEsB6nA
    typename: tezlandDutchAuctions

datasources:
  tzkt_mainnet:
    kind: tzkt
    url: ${TZKT_URL:-https://api.tzkt.io}
  local_ipfs:
    kind: ipfs
    url: ${IPFS_GATEWAY:-http://localhost:8080/ipfs}
    http:
      retry_count: 10
      retry_sleep: 2
      retry_multiplier: 2

# TEMP: For now on rollback wipe and reindex
advanced:
  reindex:
    rollback: wipe
    
indexes:
  tezland_mainnet:
    kind: operation
    datasource: tzkt_mainnet
    contracts: 
      - tezlandMinter
      - tezlandItems
      - tezlandPlaces
      - tezlandDutchAuctions
    handlers:

      # Dutch auctions
      - callback: on_dutch_auction_create
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: create
      - callback: on_dutch_auction_cancel
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: cancel
      - callback: on_dutch_auction_bid
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: bid

      # Minter
      - callback: on_item_mint
        pattern:
          - type: transaction
            destination: tezlandMinter
            entrypoint: mint_Item
          - type: transaction
            destination: tezlandItems
            entrypoint: mint
      - callback: on_place_mint
        pattern:
          - type: transaction
            destination: tezlandMinter
            entrypoint: mint_Place
          - type: transaction
            destination: tezlandPlaces
            entrypoint: mint

      # FA2 Item
      - callback: on_item_transfer
        pattern:
          - type: transaction
            destination: tezlandItems
            entrypoint: transfer
      - callback: on_item_burn
        pattern:
          - type: transaction
            destination: tezlandItems
            entrypoint: burn

      # FA2 Place
      - callback: on_place_transfer
        pattern:
          - type: transaction
            destination: tezlandPlaces
            entrypoint: transfer

hooks:
  retry_metadata:
    callback: retry_metadata
    atomic: False

jobs:
  retry_metadata:
    hook: retry_metadata
    daemon: true
    #interval: 1  # in seconds