spec_version: 1.2
package: landex

database:
  kind: sqlite
  path: landex.sqlite3

# Contracts on testnet
contracts:
  tezlandItems:
    address: KT1SdBmADH7YTdbio8QnhWXKJ3eBtzxprr49
    typename: tezlandItems

  tezlandPlaces:
    address: KT1B8g74YtySkTnxNHo3hgab8L3u3kqvKkmM
    typename: tezlandPlaces

  tezlandDAO:
    address: KT1SULJeVxroBuktQgkC8rBcp852fayGuCWu
    typename: tezlandDAO

  tezlandWorld:
    address: KT1KX5WDu12Fje2joZnHFgR5un7jovZRWNiA
    typename: tezlandWorld

  tezlandMinter:
    address: KT1BjayXEp7xizV366L4Ps4XFyRJTNsnyGzC
    typename: tezlandMinter

  tezlandDutchAuctions:
    address: KT1Kusg2CCTtUCvhasLD8x7g6hNhcztxN8ri
    typename: tezlandDutchAuctions

datasources:
  tzkt_mainnet:
    kind: tzkt
    url: ${TZKT_URL:-https://api.hangzhou2net.tzkt.io}
  local_ipfs:
    kind: ipfs
    url: ${IPFS_GATEWAY:-http://localhost:8080/ipfs}
    http:
      retry_count: 10
      retry_sleep: 2
      retry_multiplier: 2

# TEMP: For now on rollback wipe and reindex
advanced:
  reindex:
    rollback: wipe
    
indexes:
  tezland_mainnet:
    kind: operation
    datasource: tzkt_mainnet
    contracts: 
      - tezlandMinter
      - tezlandItems
      - tezlandPlaces
      - tezlandDutchAuctions
    handlers:

      # Dutch auctions
      - callback: on_dutch_auction_create
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: create
      - callback: on_dutch_auction_cancel
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: cancel
      - callback: on_dutch_auction_bid
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: bid

      # Minter
      - callback: on_item_mint
        pattern:
          - type: transaction
            destination: tezlandMinter
            entrypoint: mint_Item
          - type: transaction
            destination: tezlandItems
            entrypoint: mint
      - callback: on_place_mint
        pattern:
          - type: transaction
            destination: tezlandMinter
            entrypoint: mint_Place
          - type: transaction
            destination: tezlandPlaces
            entrypoint: mint

      # FA2 Item
      - callback: on_item_transfer
        pattern:
          - type: transaction
            destination: tezlandItems
            entrypoint: transfer
      - callback: on_item_burn
        pattern:
          - type: transaction
            destination: tezlandItems
            entrypoint: burn

      # FA2 Place
      - callback: on_place_transfer
        pattern:
          - type: transaction
            destination: tezlandPlaces
            entrypoint: transfer

hooks:
  retry_metadata:
    callback: retry_metadata
    atomic: False

jobs:
  retry_metadata:
    hook: retry_metadata
    daemon: true
    #interval: 1  # in seconds