spec_version: 1.2
package: landex

database:
  kind: sqlite
  path: landex.sqlite3

# No contracts actually deployed on mainnet yet. specify in ...dev.local.yml
contracts:
  tezlandItems:
    address: KT1000000000000000000000000000000000
    typename: tezlandItems

  tezlandPlaces:
    address: KT1000000000000000000000000000000000
    typename: tezlandPlaces

  tezlandMinter:
    address: KT1000000000000000000000000000000000
    typename: tezlandMinter

  tezlandDutchAuctions:
    address: KT1000000000000000000000000000000000
    typename: tezlandDutchAuctions

datasources:
  tzkt_mainnet:
    kind: tzkt
    url: ${TZKT_URL:-http://0.0.0.0:5020}
    
indexes:
  tezland_mainnet:
    kind: operation
    datasource: tzkt_mainnet
    contracts: 
      - tezlandMinter
      - tezlandItems
      - tezlandPlaces
      - tezlandDutchAuctions
    handlers:

      # Dutch auctions
      - callback: on_dutch_auction_create
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: create
      - callback: on_dutch_auction_cancel
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: cancel
      - callback: on_dutch_auction_bid
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: bid

      # Minter
      - callback: on_item_mint
        pattern:
          - type: transaction
            destination: tezlandMinter
            entrypoint: mint_Item
          - type: transaction
            destination: tezlandItems
            entrypoint: mint
      - callback: on_place_mint
        pattern:
          - type: transaction
            destination: tezlandMinter
            entrypoint: mint_Place
          - type: transaction
            destination: tezlandPlaces
            entrypoint: mint

      # FA2 Item
      - callback: on_item_transfer
        pattern:
          - type: transaction
            destination: tezlandItems
            entrypoint: transfer
      - callback: on_item_burn
        pattern:
          - type: transaction
            destination: tezlandItems
            entrypoint: burn

      # FA2 Place
      - callback: on_place_transfer
        pattern:
          - type: transaction
            destination: tezlandPlaces
            entrypoint: transfer

hooks:
  retry_metadata:
    callback: retry_metadata
    atomic: False

jobs:
  retry_metadata:
    hook: retry_metadata
    interval: 120  # in seconds