spec_version: 1.2
package: landex

database:
  kind: sqlite
  path: landex.sqlite3

# Contracts on testnet
contracts:
  tezlandItems:
    address: KT1M3Wji7k87JhH86RFmJeBp9vrTXpsCjNQ9
    typename: tezlandItems

  tezlandPlaces:
    address: KT1DJfnW5dPWUCyF5F86FvEdM129pYiFXUEL
    typename: tezlandPlaces

  tezlandDAO:
    address: KT1TLT1wipsFZkF43kcpyLNQBXpZiNyZb51o
    typename: tezlandDAO

  tezlandWorld:
    address: KT1TUpa5hrfZTR4MiHLQnryAn92NhH5ADXhw
    typename: tezlandWorld

  tezlandMinter:
    address: KT1Nh6Jv5G4CeG1YkhZsMSBwL6vQufiq1TZ9
    typename: tezlandMinter

  tezlandDutchAuctions:
    address: KT1Wwor4wSo5pEJbfviMKF3pjuoJw9pkJhks
    typename: tezlandDutchAuctions

datasources:
  tzkt_mainnet:
    kind: tzkt
    url: ${TZKT_URL:-https://api.hangzhou2net.tzkt.io}
  local_ipfs:
    kind: ipfs
    url: ${IPFS_GATEWAY:-http://localhost:8080/ipfs}
    http:
      retry_count: 10
      retry_sleep: 2
      retry_multiplier: 2
    
indexes:
  tezland_mainnet:
    kind: operation
    datasource: tzkt_mainnet
    contracts: 
      - tezlandMinter
      - tezlandItems
      - tezlandPlaces
      - tezlandDutchAuctions
    handlers:

      # Dutch auctions
      - callback: on_dutch_auction_create
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: create
      - callback: on_dutch_auction_cancel
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: cancel
      - callback: on_dutch_auction_bid
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: bid

      # Minter
      - callback: on_item_mint
        pattern:
          - type: transaction
            destination: tezlandMinter
            entrypoint: mint_Item
          - type: transaction
            destination: tezlandItems
            entrypoint: mint
      - callback: on_place_mint
        pattern:
          - type: transaction
            destination: tezlandMinter
            entrypoint: mint_Place
          - type: transaction
            destination: tezlandPlaces
            entrypoint: mint

      # FA2 Item
      - callback: on_item_transfer
        pattern:
          - type: transaction
            destination: tezlandItems
            entrypoint: transfer
      - callback: on_item_burn
        pattern:
          - type: transaction
            destination: tezlandItems
            entrypoint: burn

      # FA2 Place
      - callback: on_place_transfer
        pattern:
          - type: transaction
            destination: tezlandPlaces
            entrypoint: transfer

hooks:
  retry_metadata:
    callback: retry_metadata
    atomic: False

jobs:
  retry_metadata:
    hook: retry_metadata
    daemon: true
    #interval: 1  # in seconds