spec_version: 1.2
package: landex

database:
  kind: sqlite
  path: landex.sqlite3

# Contracts on mainnet
contracts:
  tezlandItems:
    address: KT1TKFWDiMk35c5n94TMmLaYksdXkHuaL112
    typename: tezlandFA2Fungible

  tezlandItemsV2:
    address: KT1Fw3CTyc3b1tQDhQrvq6vCd4wNphSm1qgg
    typename: tezlandFA2FungibleV2

  tezlandPlaces:
    address: KT1G6bH9NVDp8tSSz7FzDUnCgbJwQikxtUog
    typename: tezlandFA2NFT

  tezlandPlacesV2:
    address: KT1AxxoqSJ8BfjCMZ3iQxAJXj1nabZWx9xkb
    typename: tezlandFA2NFTV2NonstandardTransfer

  tezlandInteriors:
    address: KT1JgXBVefMv4bz5FnXM7XB8Yx4HejKvsXgE
    typename: tezlandFA2NFTV2NonstandardTransfer

  tezlandDAO:
    address: KT1Xag669km4EXaQPi3GH9fcofjvPnJneuaL
    typename: tezlandDAO

  tezlandWorld:
    address: KT1EuSjJgQRGXM18TEu1WaMRyshPSkSCg11n
    typename: tezlandWorld

  tezlandWorldV2:
    address: KT1977zpPmwDqiDRqoGS47HRhQUaxcQigVYc
    typename: tezlandWorldV2
    
  tezlandMinter:
    address: KT1GmLfej8mFrfB3bRSoc1fTuCa9eQHJw8Qi
    typename: tezlandMinter

  tezlandMinterV2:
    address: KT1Na8LVvrzuBXuwCiEDgRGssq9yBZvSjfUV
    typename: tezlandMinterV2

  tezlandDutchAuctions:
    address: KT1WmMn55RjXwk5Xb4YE6asjy5BvMiEsB6nA
    typename: tezlandDutchAuctions

  tezlandDutchAuctionsV2:
    address: KT1VFX9Dzt1QBiBNh6fnepoYdFeE4GeNtkKG
    typename: tezlandDutchAuctionsV2
    
  tezlandFactory:
    address: KT1Qo5rBCWDCqo124ccdWsd4TKN8NAUVpHZR
    typename: tezlandFactory
    
  tezlandRegistry:
    address: KT1X4HDjXt3fdmSHpJSj7yzGxK3HALRduufF
    typename: tezlandRegistry

datasources:
  tzkt_mainnet:
    kind: tzkt
    url: ${TZKT_URL:-https://api.tzkt.io}

# TEMP: For now on rollback wipe and reindex
advanced:
  reindex:
    rollback: wipe
    schema_modified: wipe
    # alternatively to rollback reindex we could also emit a
    # manual type and wipe on that.
    #manual: wipe

# NOTE: indexes are mutable and independent of each other,
# so they need to contain all their dependencies.
indexes:
  tezland_mainnet:
    kind: operation
    datasource: tzkt_mainnet
    contracts: 
      - tezlandMinter
      - tezlandItems
      - tezlandItemsV2
      - tezlandPlaces
      - tezlandInteriors
      - tezlandPlacesV2
      - tezlandDutchAuctions
      - tezlandDutchAuctionsV2
      - tezlandWorld
      - tezlandWorldV2
    handlers:
      # World V2
      - callback: world_v2.on_place_items
        pattern:
          - type: transaction
            destination: tezlandWorldV2
            entrypoint: place_items
      - callback: world_v2.on_remove_items
        pattern:
          - type: transaction
            destination: tezlandWorldV2
            entrypoint: remove_items
      - callback: world_v2.on_set_item_data
        pattern:
          - type: transaction
            destination: tezlandWorldV2
            entrypoint: set_item_data
      - callback: world_v2.on_get_item
        pattern:
          - type: transaction
            destination: tezlandWorldV2
            entrypoint: get_item
      - callback: world_v2.on_set_permissions
        pattern:
          - type: transaction
            destination: tezlandWorldV2
            entrypoint: set_permissions
      - callback: world_v2.on_migration
        pattern:
          - type: transaction
            destination: tezlandWorldV2
            entrypoint: migration

      # World
      - callback: world.on_place_items
        pattern:
          - type: transaction
            destination: tezlandWorld
            entrypoint: place_items
      - callback: world.on_remove_items
        pattern:
          - type: transaction
            destination: tezlandWorld
            entrypoint: remove_items
      - callback: world.on_set_item_data
        pattern:
          - type: transaction
            destination: tezlandWorld
            entrypoint: set_item_data
      - callback: world.on_get_item
        pattern:
          - type: transaction
            destination: tezlandWorld
            entrypoint: get_item

      # Dutch auctions V2
      - callback: dutch_auction_v2.on_create
        pattern:
          - type: transaction
            destination: tezlandDutchAuctionsV2
            entrypoint: create
      - callback: dutch_auction_v2.on_cancel
        pattern:
          - type: transaction
            destination: tezlandDutchAuctionsV2
            entrypoint: cancel
      - callback: dutch_auction_v2.on_bid
        pattern:
          - type: transaction
            destination: tezlandDutchAuctionsV2
            entrypoint: bid
      - callback: dutch_auction_v2.on_manage_wl
        pattern:
          - type: transaction
            destination: tezlandDutchAuctionsV2
            entrypoint: manage_whitelist

      # Dutch auctions
      - callback: dutch_auction.on_create
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: create
      - callback: dutch_auction.on_cancel
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: cancel
      - callback: dutch_auction.on_bid
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: bid
      - callback: dutch_auction.on_manage_wl
        pattern:
          - type: transaction
            destination: tezlandDutchAuctions
            entrypoint: manage_whitelist

      # FA2 Item
      - callback: on_item_transfer
        pattern:
          - type: transaction
            destination: tezlandItems
            entrypoint: transfer
      - callback: on_item_mint
        pattern:
          - type: transaction
            destination: tezlandItems
            entrypoint: mint
      - callback: on_item_burn
        pattern:
          - type: transaction
            destination: tezlandItems
            entrypoint: burn

      # FA2 Item V2
      - callback: on_item_transfer
        pattern:
          - type: transaction
            destination: tezlandItemsV2
            entrypoint: transfer
      - callback: on_item_v2_mint
        pattern:
          - type: transaction
            destination: tezlandItemsV2
            entrypoint: mint
      - callback: on_item_burn
        pattern:
          - type: transaction
            destination: tezlandItemsV2
            entrypoint: burn

      # FA2 Place
      - callback: on_place_transfer
        pattern:
          - type: transaction
            destination: tezlandPlaces
            entrypoint: transfer
      - callback: on_place_mint
        pattern:
          - type: transaction
            destination: tezlandPlaces
            entrypoint: mint

      # FA2 Place V2
      - callback: on_place_transfer
        pattern:
          - type: transaction
            destination: tezlandPlacesV2
            entrypoint: transfer_tokens
      - callback: on_place_mint
        pattern:
          - type: transaction
            destination: tezlandPlacesV2
            entrypoint: mint

      # FA2 Interior
      - callback: on_place_transfer
        pattern:
          - type: transaction
            destination: tezlandInteriors
            entrypoint: transfer_tokens
      - callback: on_place_mint
        pattern:
          - type: transaction
            destination: tezlandInteriors
            entrypoint: mint

hooks:
  #retry_metadata:
  #  callback: retry_metadata
  #  atomic: False
  run_backups:
    callback: run_backups
    atomic: False
  #simulate_reorg:
  #  callback: simulate_reorg
  #  atomic: True

jobs:
  #retry_metadata:
  #  hook: retry_metadata
  #  daemon: true
    #interval: 1  # in seconds
  run_backups:
    hook: run_backups
    interval: 1800 # in seconds, 30 minutes
  #simulate_reorg:
  #  hook: simulate_reorg
  #  interval: 90  # in seconds