version: "3.7"

services:
  tezland-indexer:
    command: "-c dipdup.yml -c dipdup.docker.yml run"
    build:
      network: bcdbox_default
      args:
        - TZKT_URL=https://api.tzkt.io
    environment:
      - TZKT_URL=https://api.tzkt.io
    volumes:
      - ./tz1aND_metadata.staging:/indexer/tz1aND_metadata

  tezland-metadata-processing:
    command: ["--env", "staging"]

  tezland-hasura:
    ports:
      - 127.0.0.1:42000:8080
    environment:
      - HASURA_GRAPHQL_CORS_DOMAIN=*

  db-dipdup:
    ports:
      - 127.0.0.1:15435:15435

networks:
  default:
    external: true
    name: bcdbox_default