version: "3.7"

services:
  tezland-indexer:
    container_name: tezland-indexer
    image: tezland-indexer:$TAG
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TZKT_URL=https://api.tzkt.io
    depends_on:
      db-dipdup:
        condition: service_healthy
      tezland-hasura:
        condition: service_started
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - ADMIN_SECRET=${ADMIN_SECRET:-changeme}
      - TOKEN_METADATA_DIR=/indexer/tz1aND_metadata
      - IPFS_GATEWAY=https://cloudflare-ipfs.com/ipfs
      - TZKT_URL=https://api.tzkt.io
    volumes:
      - ./tz1aND_metadata:/indexer/tz1aND_metadata

  db-dipdup:
    container_name: db-dipdup
    image: postgres:13
    restart: always
    volumes:
      - db-dipdup:/var/lib/postgres/data
    environment: 
      - POSTGRES_USER=dipdup
      - POSTGRES_DB=dipdup
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - PGPORT=15435
    expose:
      - 15435
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dipdup"]
      interval: 10s
      timeout: 5s
      retries: 5

  tezland-hasura:
    container_name: tezland-hasura
    image: hasura/graphql-engine:v2.1.1
    depends_on:
      db-dipdup:
        condition: service_healthy
    restart: always
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://dipdup:${POSTGRES_PASSWORD:-changeme}@db-dipdup:15435/dipdup
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=false
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
      - HASURA_GRAPHQL_ADMIN_SECRET=${ADMIN_SECRET:-changeme}
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=user
  
volumes:
  db-dipdup:

networks:
  default:
    name: tz1and_prod