version: "3.7"

services:
  tezland-indexer:
    command: "-c dipdup.yml -c dipdup.docker.yml run"
    build:
      network: bcdbox_default
      args:
        - TZKT_URL=https://api.tzkt.io
    environment:
      - IPFS_GATEWAY=http://ipfs-node:8080/ipfs # as defined in tezland sanbox
      - TZKT_URL=https://api.tzkt.io
    volumes:
      - ./tz1aND_metadata.staging:/indexer/tz1aND_metadata

  tezland-metadata:
    environment:
      - LOCAL_IPFS_NODE=http://localhost:8080

  tezland-hasura:
    ports:
      - 127.0.0.1:42000:8080
    environment:
      - HASURA_GRAPHQL_CORS_DOMAIN=*

networks:
  default:
    external: true
    name: bcdbox_default