version: "3.7"

services:
  tezland-indexer:
    container_name: tezland-indexer
    image: tezland/indexer:$TAG
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TZKT_URL=https://api.tzkt.io
    depends_on:
      db-dipdup:
        condition: service_healthy
      tezland-hasura:
        condition: service_started
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - HASURA_ADMIN_SECRET=${HASURA_ADMIN_SECRET:-changeme}
      - TOKEN_METADATA_DIR=/indexer/tz1aND_metadata
      - TZKT_URL=https://api.tzkt.io
    volumes:
      - ./tz1aND_metadata:/indexer/tz1aND_metadata

  tezland-metadata:
    container_name: tezland-metadata
    image: tezland/metadata:latest
    restart: always
    depends_on:
      db-dipdup:
        condition: service_healthy
      tezland-hasura:
        condition: service_started
    restart: always
    environment:
      - DATASOURCE=tzkt_mainnet
      - ITEMS_CONTRACT=KT1TKFWDiMk35c5n94TMmLaYksdXkHuaL112
      - PLACES_CONTRACT=KT1G6bH9NVDp8tSSz7FzDUnCgbJwQikxtUog
      - HASURA_HOST=tezland-hasura
      - HASURA_ADMIN_SECRET=${HASURA_ADMIN_SECRET:-changeme}
      - DB_HOST=db-dipdup
      - DB_PORT=15435
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=metadata
    entrypoint: sh -c "sleep 60 && /go/bin/dipdup-metadata"

  db-dipdup:
    container_name: db-dipdup
    image: postgres:13
    restart: always
    volumes:
      - db-dipdup:/var/lib/postgresql/data
      - ./docker_postgresql_multiple_databases.sh:/docker-entrypoint-initdb.d/docker_postgresql_multiple_databases.sh
    environment: 
      - POSTGRES_USER=dipdup
      - POSTGRES_DB=dipdup
      - POSTGRES_MULTIPLE_DATABASES=hasurametadata,dipdup:metadata,dipdup
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - PGPORT=15435
    expose:
      - 15435
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dipdup -d dipdup && pg_isready -U dipdup -d metadata && pg_isready -U dipdup -d hasurametadata"]
      interval: 10s
      timeout: 5s
      retries: 5

  tezland-hasura:
    container_name: tezland-hasura
    image: hasura/graphql-engine:v2.4.0
    depends_on:
      db-dipdup:
        condition: service_healthy
    restart: always
    environment:
      - HASURA_GRAPHQL_METADATA_DATABASE_URL=postgres://dipdup:${POSTGRES_PASSWORD:-changeme}@db-dipdup:15435/hasurametadata
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=false
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_ADMIN_SECRET:-changeme}
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=user
      - HASURA_GRAPHQL_CORS_DOMAIN=https://*.tz1and.com

volumes:
  db-dipdup:

networks:
  default:
    name: tz1and_prod