# generated by datamodel-codegen:
#   filename:  burn.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class BurnParameterItem(BaseModel):
    class Config:
        extra = Extra.forbid

    from_: str
    amount: str
    token_id: str


class BurnParameter(BaseModel):
    __root__: List[BurnParameterItem]
